name: CD Pipeline to Google Cloud Run (staging and production)
on:
  workflow_dispatch:
  release:
    types: published
  push:
    branches:
      - staging

env:
  PORT: 5001
jobs:
  test:
    runs-on: ubuntu-latest
    name: Setup project test and build project
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Test application
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    name: Setup project, Authorize GitHub actions to GCP and Docker Hub, and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate for GCP
        id: gcp-auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authenticate for Docker Hub
        id: docker-auth
        env:
          D_USER: ${{secrets.DOCKER_USER}}
          D_PASS: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $D_USER -p $D_PASS

      - name: Build and tag Image
        run: |
          docker build -t ${{vars.IMAGE}} .

      - name: Push the image to Docker hub
        run: |
          docker push ${{vars.IMAGE}}

      - name: Enable the Billing API
        run: |
          gcloud services enable cloudbilling.googleapis.com --project=${{secrets.GCP_PROJECT_ID}}

      - name: Deploy to GCP Run - Production environment (If a new release was published from the master branch)
        if: github.event_name == 'release' && github.event.action == 'published' && github.event.release.target_commitish == 'main'
        run: |
          gcloud run deploy ${{vars.GCR_PROJECT_NAME}} \
          --region ${{vars.GCR_REGION}} \
          --image ${{vars.IMAGE}} \
          --platform "managed" \
          --allow-unauthenticated \
          --set-env-vars PORT=${{env.PORT}}

      - name: Deploy to GCP Run - Staging environment (If a push was made to the staging branch, e.g. from a successful PR)
        if: github.ref != 'refs/heads/main'
        run: |
          gcloud run deploy ${{vars.GCR_PROJECT_NAME}} \
          --region ${{vars.GCR_REGION}} \
          --image ${{vars.IMAGE}} \
          --platform "managed" \
          --allow-unauthenticated \
          --no-traffic \
          --tag staging \
          --set-env-vars PORT=${{env.PORT}}
